services:
  server:
    build:
      context: .
    env_file:
      - .env.test
    # command: sh -c "npm run migrate:dev && npx nodemon -L server.js"
    command: sh -c "npm run build:prod && node server.js"

    depends_on:
      db:
        condition: service_healthy

    # volumes:
    #   - .:/usr/src/app
  db:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prisma-network
    environment:
      - POSTGRES_DB=bostonhacksapidev
      - POSTGRES_PASSWORD=bostonhacksapidev
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env.test
    networks:
      - prisma-network
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_started
volumes:
  db-data:
networks:
  prisma-network:
    name: prisma-network
# secrets:
#   db-password:
#     file: db/password.txt


  