name: bostonhacks-api_test
services:
  test-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bostonhacksapitest
      - POSTGRES_PASSWORD=bostonhacksapitest
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # No volume needed for test database

  test-app:
    build:
      context: .
    env_file:
      - .env.test
    depends_on:
      test-db:
        condition: service_healthy
    # command: sh -c "npm install && npx eslint . && jest --testTimeout=5000 --detectOpenHandles"    # No volume needed for test app
    command: sh -c "npm install && npx eslint . && npx prisma migrate deploy && npx prisma generate && npm test"
