services:
  server:
    build:
      context: .
    env_file:
      - .env.development
    ports:
      - 8000:8000
    command: sh -c "npx prisma migrate deploy && npx prisma generate & npx nodemon -L server.js"
    # command: sh -c "npm run build:prod && node server.js"

    depends_on:
      db:
        condition: service_healthy

    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
        - action: rebuild
          path: package.json

    # volumes:
    #   - .:/usr/src/app
  db:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bostonhacksapidev
      - POSTGRES_PASSWORD=bostonhacksapidev
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma:
    build:
      context: .
    ports: 
      - 5555:5555
    env_file:
      - .env.development
    depends_on:
        db:
          condition: service_healthy
    command: sh -c "npm run prismastudio:dev"
    

volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt


  
