name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    environment: Test
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      #
      # - name: Install dependencies
      #   run: npm ci
      #
      # - name: Check code style
      #   run: npx eslint .
      - name: Create .env.test file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test
          echo "NODE_ENV=test" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.test
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.test
          echo "GOOGLE_OAUTH_URL=${{ vars.GOOGLE_OAUTH_URL }}" >> .env.test
          echo "GOOGLE_ACCESS_TOKEN_URL=${{ vars.GOOGLE_ACCESS_TOKEN_URL }}" >> .env.test
          echo "GOOGLE_CALLBACK_URL=${{ vars.GOOGLE_CALLBACK_URL }}" >> .env.test
          echo "GOOGLE_TOKEN_INFO_URL=${{ vars.GOOGLE_TOKEN_INFO_URL }}" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test
          echo "DATABASE_DIRECT_URL=${{ secrets.DATABASE_DIRECT_URL }}" >> .env.test
          echo "EMAIL_SIGNUP=true" >> .env.test
          echo "LOG_LEVEL=debug" >> .env.test
          echo "PORT=8000" >> .env.test
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} >> .env.test
          echo "AZURE_CONTAINER_NAME=resumes" >> .env.test
          echo "AZURE_STORAGE_ACCOUNT_NAME=bostonhacksapi" >> .env.test
          echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} >> .env.test

      
      - name: Run Docker Compose for tests and linting
        env:
          NODE_ENV: test
        run: npm run docker:test
    
